language: node_js
node_js:
  - 'lts/*'
os:
  - linux
  - osx

matrix:
  fast_finish: true

services:
  - xvfb
  - docker

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=:99.0;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run cucumber; fi
  - npm test
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
          --env-file <(env | grep -vE '\r|\n' | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \
          --env ELECTRON_CACHE="/root/.cache/electron" \
          --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
          -v ${PWD}:/project \
          -v ~/.cache/electron:/root/.cache/electron \
          -v ~/.cache/electron-builder:/root/.cache/electron-builder \
          electronuserland/builder:wine-02.17 \
          /bin/bash -c "npm run release"
    else
      npm run release:osx
    fi
